### PR TITLE
Update Stringtable and Civilian Penalty Script

### PR DESCRIPTION
**Pull request by Wyqer**
And again -> added missing german strings

### CODE REVIEW

**Comment by GreuhZbug** [comment]
Thanks a lot :)
I will merge your changes in the next version

**Comment by Wyqer** [comment]
Added a script on the base of the ammo bounty for a penalty for killing
civilians. Also added the stringtable for this script and a mission
parameter to enable or disable the penalty.

**Comment by GreuhZbug** [comment]
You should have made separate pull requests for each feature (new translations / civilian killing penalty), but nevermind I'll just accept both. Thanks for your contribution, much appreciated :+1:

**Comment by GreuhZbug** [comment]
I moved the penalty value into gameplay constants so people can modify it easily. Also changed its default value to 20.

**Comment by Wyqer** [comment]
Ok, thanks for accepting my script. Makes me proud that i can contribute something to your great work. If I want to contribute some more in the future I'll have a look to create pulls for each feature.

**Pull request merged**
